### ISSUE TITLE
infinity brok on live 11

### ISSUE THREAD

**Issue by pnxl** [mat1jaczyyy/outbreak#12]
yes it did brok

A

**Comment by mat1jaczyyy** [comment]
very helpful issue

**Comment by mat1jaczyyy** [comment]
![image](https://user-images.githubusercontent.com/13300194/153021413-300ca15c-2b83-410c-abb7-49d95418f5d0.png)
ratio

**Comment by pnxl** [comment]
ok

**Comment by pnxl** [comment]
> very helpful issue

well i dont really have anything else to say
infinity just holds the lights but in live 11 it doesnt so

yes

**Comment by mat1jaczyyy** [comment]
https://www.youtube.com/watch?v=tTre9iVVHgU not my problem

**Comment by pnxl** [comment]
bruh tf

**Comment by mat1jaczyyy** [comment]
its literally not my problem and i cant even do anything if i wanted

**Comment by pnxl** [comment]
yea i gotchu
ableton bad
