### ISSUE TITLE
Appears to have corrupted the preference files for Ableton Live... Ableton crashed and now will no longer open.

### ISSUE THREAD

**Issue by FigrHed** [mat1jaczyyy/outbreak#13]
Google chrome crashed at the same time and also will no longer open.
Not sure how to narrow dow n the problem.

**Comment by mat1jaczyyy** [comment]
Sorry for late response. You might be able to find some crash reports at `%APPDATA%\Ableton\Live Reports\` assuming you're on Windows?

**Comment by FigrHed** [comment]
Yes I have one, I'm on Mac though. I ended up fixing the problem by completely deleting all my Preference files and undo history for both chrome and Live. Now Outbreak appear to work fine s I have no idea if it was caused by m4l glitches or not... it might have been a coincidence. My spotify also no longer works since the same time!!! Bizarre.

**Comment by FigrHed** [comment]
[Ableton Crash Report 2022-07-21 150501 Live 10.1.30.zip](https://github.com/mat1jaczyyy/outbreak/files/9186222/Ableton.Crash.Report.2022-07-21.150501.Live.10.1.30.zip)

**Comment by mat1jaczyyy** [comment]
I vaguely remember this happening to me as well fairly recently separately from Outbreak... but I don't remember what was the trigger for it. I'll see if there's anything useful in your report. Glad you got it sorted!

**Comment by mat1jaczyyy** [comment]
@FigrHed 

```
2022-07-21T15:02:00.269744: error: Directory: failed to delete file/folder "/Users/bonedaddy/Library/Preferences/Ableton/Live 10.1.30/BaseFiles": Permission denied
2022-07-21T15:02:00.269765: info: Exception: “/Users/bonedaddy/Library/Preferences/Ableton/Live 10.1.30/BaseFiles” cannot be deleted.
```

Seems to have been a permission problem in a low-level routine, very odd stuff, I'd send your crash report to Ableton if I were you ;)
