### ISSUE TITLE
Frozen multisamples

### ISSUE THREAD

**Issue by Tuchan** [mat1jaczyyy/outbreak#4]
Well... sometimes when i got multi reset on the first place in midi effect rack and its on, my multisamples are frozen but when its off it works completely fine.

**Comment by mat1jaczyyy** [comment]
Well, "sometimes" does not help me. What exactly is the first place in the midi effect rack? First chain, or located before the midi effect rack?

**Comment by mat1jaczyyy** [comment]
User placed Multi Reset at end of Track.
